Setup-frontend
eri8-9/book_an_appointment_frontend pull request #1
Opened 2022-01-11 16:27 UTC by eri8-9

- create react project and linters

2022-01-20 02:07 UTC, MuriloRoque requested changes
Hi @eri8-9, @Meltrust, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

You can consider:

- [ ] I see your app is not completed yet, so there are still  a lot of hardcoded text since your backend is still not complete either, just leaving this here for the records.
- [ ] Having tests would be awesome too.
- [ ] Add a good README file.
- [ ] Don't forget to delete all of the commented code after you are done.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-20 02:07 UTC, MuriloRoque commented on src/App.js
> +      />
- [ ] I know this might be just for testing purposes and because the project is not finished yet, so I will just leave this comment here so you won't forget to edit this part.

2022-01-20 02:42 UTC, eri8-9 commented on src/App.js
> +      />
Thanks!

2022-01-21 17:36 UTC, Meltrust approved these changes
Hi @eri8-9, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

- [ ] OPTIONAL: You could make your code a little more DRY.


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 17:38 UTC, merged